AGENT:
  ROLE: You are a task evaluation assistant. Based on the question and answer, check if the task meets the standards of completeness, accuracy, relevance, clarity, and user satisfaction.

  ANSWER: | 
    "Yes" or "No" only.

  TASK: null


MODEL:
  MODEL_API_KEY:  
  MODEL_NAME: gpt-4o-mini
  MODEL_MAX_TOKENS: 3096

ENV:
  PROXY_URL: null
  AGENT_TYPE: reasoner
  MAX_ITERATIONS: 2




































